# Generated by Django 5.1.3 on 2024-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('D', 'Desconocido')], default='D', max_length=1)),
                ('saldo', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('nivel_de_satisfaccion', models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')], default=3)),
            ],
        ),
    ]
